# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 558)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/small_donkey.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 191, 291))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/blue_streets.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 271, 311))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/adlai_button.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(520, 50, 111, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 80, 181, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/ragtime_cowboy.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 140, 81, 121))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/cowboy_large.jpg"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 280, 141, 19))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 31))
        self.menubar.setObjectName("menubar")
        self.menuTurf = QtWidgets.QMenu(self.menubar)
        self.menuTurf.setObjectName("menuTurf")
        self.menuVoters = QtWidgets.QMenu(self.menubar)
        self.menuVoters.setObjectName("menuVoters")
        self.menuContacts = QtWidgets.QMenu(self.menubar)
        self.menuContacts.setObjectName("menuContacts")
        self.menuImport = QtWidgets.QMenu(self.menuContacts)
        self.menuImport.setObjectName("menuImport")
        self.menuClean_Up = QtWidgets.QMenu(self.menuContacts)
        self.menuClean_Up.setObjectName("menuClean_Up")
        self.menuGroups = QtWidgets.QMenu(self.menubar)
        self.menuGroups.setObjectName("menuGroups")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionWorksheet = QtWidgets.QAction(MainWindow)
        self.actionWorksheet.setObjectName("actionWorksheet")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionImport_2 = QtWidgets.QAction(MainWindow)
        self.actionImport_2.setObjectName("actionImport_2")
        self.actionBattle_Stations = QtWidgets.QAction(MainWindow)
        self.actionBattle_Stations.setObjectName("actionBattle_Stations")
        self.actionExport_2 = QtWidgets.QAction(MainWindow)
        self.actionExport_2.setObjectName("actionExport_2")
        self.actionCounty = QtWidgets.QAction(MainWindow)
        self.actionCounty.setObjectName("actionCounty")
        self.actionSpreadsheet = QtWidgets.QAction(MainWindow)
        self.actionSpreadsheet.setObjectName("actionSpreadsheet")
        self.actionEntry_Form = QtWidgets.QAction(MainWindow)
        self.actionEntry_Form.setObjectName("actionEntry_Form")
        self.actionBattle_Stations_2 = QtWidgets.QAction(MainWindow)
        self.actionBattle_Stations_2.setObjectName("actionBattle_Stations_2")
        self.actionEmail_Dups = QtWidgets.QAction(MainWindow)
        self.actionEmail_Dups.setObjectName("actionEmail_Dups")
        self.actionPhone_Dups = QtWidgets.QAction(MainWindow)
        self.actionPhone_Dups.setObjectName("actionPhone_Dups")
        self.actionName_Address_Dups = QtWidgets.QAction(MainWindow)
        self.actionName_Address_Dups.setObjectName("actionName_Address_Dups")
        self.actionName_Only_Dups = QtWidgets.QAction(MainWindow)
        self.actionName_Only_Dups.setObjectName("actionName_Only_Dups")
        self.actionSync_with_Voters = QtWidgets.QAction(MainWindow)
        self.actionSync_with_Voters.setObjectName("actionSync_with_Voters")
        self.actionTurf = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTurf.setIcon(icon1)
        self.actionTurf.setObjectName("actionTurf")
        self.actionVoters = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/voters.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVoters.setIcon(icon2)
        self.actionVoters.setObjectName("actionVoters")
        self.actionContacts = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/contacts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContacts.setIcon(icon3)
        self.actionContacts.setObjectName("actionContacts")
        self.actionGroups = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/groups.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGroups.setIcon(icon4)
        self.actionGroups.setObjectName("actionGroups")
        self.menuVoters.addAction(self.actionImport)
        self.menuVoters.addAction(self.actionWorksheet)
        self.menuVoters.addAction(self.actionExport)
        self.menuImport.addAction(self.actionCounty)
        self.menuImport.addAction(self.actionSpreadsheet)
        self.menuImport.addAction(self.actionEntry_Form)
        self.menuClean_Up.addAction(self.actionEmail_Dups)
        self.menuClean_Up.addAction(self.actionPhone_Dups)
        self.menuClean_Up.addAction(self.actionName_Address_Dups)
        self.menuClean_Up.addAction(self.actionName_Only_Dups)
        self.menuClean_Up.addAction(self.actionSync_with_Voters)
        self.menuContacts.addAction(self.menuImport.menuAction())
        self.menuContacts.addAction(self.actionBattle_Stations_2)
        self.menuContacts.addAction(self.menuClean_Up.menuAction())
        self.menubar.addAction(self.menuTurf.menuAction())
        self.menubar.addAction(self.menuVoters.menuAction())
        self.menubar.addAction(self.menuContacts.menuAction())
        self.menubar.addAction(self.menuGroups.menuAction())
        self.toolBar.addAction(self.actionTurf)
        self.toolBar.addAction(self.actionVoters)
        self.toolBar.addAction(self.actionContacts)
        self.toolBar.addAction(self.actionGroups)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bluestreets"))
        self.label_3.setText(_translate("MainWindow", "A product of"))
        self.label_6.setText(_translate("MainWindow", "All rights reserved"))
        self.menuTurf.setTitle(_translate("MainWindow", "Turf"))
        self.menuVoters.setTitle(_translate("MainWindow", "Voters"))
        self.menuContacts.setTitle(_translate("MainWindow", "Contacts"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuClean_Up.setTitle(_translate("MainWindow", "Clean Up"))
        self.menuGroups.setTitle(_translate("MainWindow", "Groups"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionWorksheet.setText(_translate("MainWindow", "Worksheet"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionImport_2.setText(_translate("MainWindow", "Import"))
        self.actionBattle_Stations.setText(_translate("MainWindow", "Battle Stations"))
        self.actionExport_2.setText(_translate("MainWindow", "Export"))
        self.actionCounty.setText(_translate("MainWindow", "County"))
        self.actionSpreadsheet.setText(_translate("MainWindow", "Spreadsheet"))
        self.actionEntry_Form.setText(_translate("MainWindow", "Entry Form"))
        self.actionBattle_Stations_2.setText(_translate("MainWindow", "Battle Stations"))
        self.actionEmail_Dups.setText(_translate("MainWindow", "Email Dups"))
        self.actionPhone_Dups.setText(_translate("MainWindow", "Phone Dups"))
        self.actionName_Address_Dups.setText(_translate("MainWindow", "Name + Address Dups"))
        self.actionName_Only_Dups.setText(_translate("MainWindow", "Name Only Dups"))
        self.actionSync_with_Voters.setText(_translate("MainWindow", "Sync with Voters"))
        self.actionTurf.setText(_translate("MainWindow", "Turf"))
        self.actionVoters.setText(_translate("MainWindow", "Voters"))
        self.actionContacts.setText(_translate("MainWindow", "Contacts"))
        self.actionGroups.setText(_translate("MainWindow", "Groups"))

import bst_rc
